fix: highlights the expression found in the email address
TheCatsLab/Telescope pull request #18
Opened 2024-06-10 10:02 UTC by AliokY

Add VisualLineElement derived type checking and
set appropriate backgroud if type is VisualLineLinkText

Refs: #12

2024-06-10 17:50 UTC, Dshauchuk requested changes

2024-06-10 17:50 UTC, Dshauchuk commented on src/Core/Controls/AvalonEdit/ColorizeAvalonEdit.cs
> +                        linkTextElement.BackgroundBrush = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#FFFF00"));
Create a constant with the highlighting color code

2024-06-11 07:37 UTC, AliokY commented on src/Core/Controls/AvalonEdit/ColorizeAvalonEdit.cs
> +                        linkTextElement.BackgroundBrush = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#FFFF00"));
Done

2024-06-11 07:40 UTC, Dshauchuk approved these changes
LGTM

2024-06-11 09:45 UTC, merged